# coding: utf-8
API_TOKEN = 'YOUR LEGACY API TOKEN xoxb-'
API_TOKEN_FIO = 'YOUR USER API TOKEN WITH FILE WRITE/READ ABIITY xoxp-'
DEFAULT_REPLY = ''
DEFAULT_CHANNEL = 'DTY96CALW'
DEFAULT_DIR = '/nfs/share/work'
PLUGINS = ['plugins']